project:
  type: website

website:
  title: "Pedro's Stats random stuff"
  navbar:
    right:
      - about.qmd
      
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

